ndctl: add key_type parameter to ndctl_dimm_remove_key stub
When keyutils is disabled, the following compilation error occurs:

  ../ndctl/dimm.c: In function ‘action_remove_passphrase’:
  ../ndctl/dimm.c:1030:16: error: too many arguments to function ‘ndctl_dimm_remove_key’
   1030 |         return ndctl_dimm_remove_key(dimm, param.master_pass ? ND_MASTER_KEY :
        |                ^~~~~~~~~~~~~~~~~~~~~
  In file included from ../ndctl/dimm.c:25:
  ../ndctl/keys.h:51:19: note: declared here
     51 | static inline int ndctl_dimm_remove_key(struct ndctl_dimm *dimm)
        |                   ^~~~~~~~~~~~~~~~~~~~~

Add the missing key_type parameter to the stub declaration so its
signature matches the declaration and call site.

[ as: update commit messsage and log ]

Fixes: a79375a9b0cd ("ndctl: Add  master-passphrase removal support")
Signed-off-by: Chen Pei <cp0613@linux.alibaba.com>
Link: https://lore.kernel.org/r/20260319015149.13719-1-cp0613@linux.alibaba.com
Signed-off-by: Alison Schofield <alison.schofield@intel.com>